checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

engines:
  rubocop:
    enabled: true
    channel: rubocop-0-58

ratings:
  paths:
  - "**.rb"

exclude_paths:
  - ci/
  - guides/
  - tasks/
  - tools/
