@ECHO OFF
C:\WINDOWS\SMARTDRV.EXE 2038 512
PROMPT $p$g
PATH C:\DOS;C:\WINDOWS;C:\WINDOWS\SYSTEM;
SET TEMP=C:\TEMP
MODE LPT1:,,P >NUL
C:\DOS\SHARE.EXE /F:150 /L:1500
C:\WINDOWS\MOUSE.COM /Y
CD \WINDOWS
WIN
