/*
 * Copyright (c) 2011-2013, Yahoo! Inc.  All rights reserved.
 * Copyrights licensed under the New BSD License.
 * See the accompanying LICENSE file for terms.
 */

/**
Internationalize the printing texts generated by the progeam.
Visit http://developer.yahoo.com/cocktails/mojito/docs/code_exs/i18n_apps.html for details.
**/

YUI.add("lang/GuideModel_en-US", function (Y, NAME) {
    'use strict';
    Y.Intl.add(
        "GuideModel",  // associated mojit
        "en-US",    // BCP 47 language tag
        // key-value pairs for this module and language
        {
            READ_DIR_ERROR_NAME: "Read dir error",
            READ_DIR_ERROR_MESSAGE: "Cannot read directory! Check file system!!",
            ERROR_CONTENT_DAMAGE: "Ooo, content is damaged in",
            ERROR_CONTENT_FETCH: "Ooo, could not fetch content for"
        }
    );
}, "3.1.0", {requires: ['intl']});