source 'https://rubygems.org'

ruby "2.2.0"

gem 'pry'
gem "rails"
gem 'sinatra'
gem 'cramp'
gem 'grape'
gem 'padrino'
gem 'camping'
gem 'cuba'
gem 'lotusrb'
gem 'nancy'
gem 'hobos', :git => 'https://www.github.com/rhgraysonii/hobos.git'
