/*
 * Copyright (c) 2011-2013, Yahoo! Inc.  All rights reserved.
 * Copyrights licensed under the New BSD License.
 * See the accompanying LICENSE file for terms.
 */

/**
Internationalize the printing texts generated by the progeam.
Visit http://developer.yahoo.com/cocktails/mojito/docs/code_exs/i18n_apps.html for details.
**/

YUI.add("lang/Read_en-US", function (Y, NAME) {
    'use strict';
    Y.Intl.add(
        "Read",  // associated mojit
        "en-US",    // BCP 47 language tag
        // key-value pairs for this module and language
        {
            ERROR_TITLE: "oh noes!"
        }
    );
}, "3.1.0", {requires: ['intl']});
