var namespaces =
[
    [ "app", "namespaceapp.html", null ],
    [ "blog1", "namespaceblog1.html", "namespaceblog1" ],
    [ "BugFixingSim", "namespaceBugFixingSim.html", null ],
    [ "com", "namespacecom.html", "namespacecom" ],
    [ "complicated_code", "namespacecomplicated__code.html", null ],
    [ "config", "namespaceconfig.html", null ],
    [ "disassemble", "namespacedisassemble.html", null ],
    [ "dmesg", "namespacedmesg.html", null ],
    [ "firstblog1", "namespacefirstblog1.html", "namespacefirstblog1" ],
    [ "fizzbuzz", "namespacefizzbuzz.html", null ],
    [ "FizzBuzz", "namespaceFizzBuzz.html", "namespaceFizzBuzz" ],
    [ "FontTagGenerator", "namespaceFontTagGenerator.html", null ],
    [ "HtmlBastardiser", "namespaceHtmlBastardiser.html", null ],
    [ "illacceptanything", "namespaceillacceptanything.html", null ],
    [ "interstellar", "namespaceinterstellar.html", null ],
    [ "libcrypto", "namespacelibcrypto.html", null ],
    [ "manage", "namespacemanage.html", null ],
    [ "memes", "namespacememes.html", null ],
    [ "ozymandias", "namespaceozymandias.html", null ],
    [ "palindrome", "namespacepalindrome.html", null ],
    [ "palindrome3", "namespacepalindrome3.html", null ],
    [ "random-xkcd", "namespacerandom-xkcd.html", null ],
    [ "recursive_cmp", "namespacerecursive__cmp.html", null ],
    [ "rng", "namespacerng.html", null ],
    [ "run", "namespacerun.html", null ],
    [ "setup", "namespacesetup.html", null ],
    [ "Sharepoint2007", "namespaceSharepoint2007.html", "namespaceSharepoint2007" ],
    [ "shoot_anything", "namespaceshoot__anything.html", null ],
    [ "skynet", "namespaceskynet.html", null ],
    [ "test_accept_all_pull_requests", "namespacetest__accept__all__pull__requests.html", null ],
    [ "toy", "namespacetoy.html", null ],
    [ "toyfs", "namespacetoyfs.html", null ]
];