name: angular2_benchmarks
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: Angular2 benchmarks
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.9.0-dev.8.0'
dependencies:
  angular2: '^<%= packageJson.version %>'
  browser: '>=0.10.0 <0.11.0'
dependency_overrides:
  angular2:
    path: ../angular2
transformers:
- angular2:
    entry_point: web/src/di/di_benchmark.dart
- $dart2js:
    minify: false
    commandLineOptions: ['--dump-info', '--trust-type-annotations', '--trust-primitives']
